# Generated by Django 6.0.2 on 2026-03-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_selected_courses_alter_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weekly_goal',
            field=models.TextField(blank=True, null=True, verbose_name='Haftalık Hedef'),
        ),
    ]
