# Generated by Django 6.0.2 on 2026-03-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_priority_subject_profile_selected_subjects_and_more'),
        ('core', '0003_profile_weekly_goal'),
    ]

    operations = [
    ]
