# Generated by Django 6.0.2 on 2026-04-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260330_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='priority_subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selected_subjects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_goal_note',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_study_days',
        ),
    ]
