# Generated by Django 6.0.2 on 2026-05-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_priority_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_topics',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Ders Konuları'),
        ),
    ]
